---
deployment:
  tasks:
    # Set deployment path to your account's public_html directory
    - export DEPLOYPATH=/home/ezfjslmy/public_html/
    
    # Deploy only the AI Portraits theme files (safer option)
    - /bin/cp -R wp-content/themes/ai-portraits $DEPLOYPATH/wp-content/themes/
    
    # Set proper file permissions for theme files
    - /bin/find $DEPLOYPATH/wp-content/themes/ai-portraits -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/wp-content/themes/ai-portraits -type d -exec chmod 755 {} \;
    
    # Ensure JavaScript files are properly set
    - /bin/chmod 644 $DEPLOYPATH/wp-content/themes/ai-portraits/js/navigation.js
    
    # Create theme-specific directories if needed
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/ai-portraits/inc
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/ai-portraits/page-templates